### PR TITLE
Added extra API endpoints

### PR DESCRIPTION
**Pull request by ShahriyarR**
* Added /delete for removing all backups
* Added checker function if the backup is already prepared or not for full backup - need to add the same thing for incremental as well.

### CODE REVIEW

**Comment by ShahriyarR** [comment]
The current version of API calls described below. 
To take a backup:
taking_backup_post_request

To list backups:
list_all_backups

To prepare backups:
prepare_backups

Check the backup status, it is successfully backed up the status will be updated:
```
{
  "backups": {
    "full": [
      {
        "2021-02-14_12-13-48": "Full-Prepared"
      }
    ],
    "inc": [
      "2021-02-14_12-14-08"
    ]
  }
}
```

To remove all backups simply call the `/delete` endpoint

**Comment by ShahriyarR** [comment]
Can be merged as the basic requirement is ready.

**Comment by gitmstoute** [comment]
@ShahriyarR So many cool features being added! I need to check out the project again!! :)

**Comment by ShahriyarR** [comment]
@gitmstoute Please checkout to release_v2.0 and smash it out :))))))

**Pull request merged**
