### PR TITLE
Default bck.conf

### PR DESCRIPTION
**Pull request by BarbzYHOOL**
Just a small attempt at making the conf easier to use and cleaner (still require a lot more rework)

### CODE REVIEW

**Comment by ShahriyarR** [comment]
Thanks for PR.
Did you check if in config parser it can parse tilda `~` and expand it to users HOME?
Because as I remember originally it was written for full path.

**Comment by BarbzYHOOL** [comment]
no I didn't :D 
Btw I might try to make it cleaner again, it was just an example, I can't help much anyway

**Comment by ShahriyarR** [comment]
The PR is not valid anymore as there are too much changes since last release.
Closing for now.

**Comment by BarbzYHOOL** [comment]
?? not really https://www.diffchecker.com/waWY1OTw

**Comment by BarbzYHOOL** [comment]
@ShahriyarR

**Comment by BarbzYHOOL** [comment]
Can you look at the diffcheck above please, it's suggestion for more logical names (the only thing you have to ignore is the TESTS part)

@ShahriyarR

**Comment by ShahriyarR** [comment]
There is no need for this patch as I have implemented new thing in release_v1.5.4.
It is going to create several options dynamically inside `~/.autoxtrabackup/autoxtrabackup.cnf ` please check it and you will see, now backup_dir for example takes `home` or `~` dynamically.
@BarbzYHOOL

**Pull request closed without merging**
