### PR TITLE
Feature 307

### PR DESCRIPTION
**Pull request by gitmstoute**
@ShahriyarR I believe this will close 307.

I haven't gotten your tests set up yet, So I haven't done any automated testing... We should be careful because it's possible I made some errors.

I was trying to drop some of these unnecessary commits (233f772, 3d8b995 in particular), and squash or clean up others, but couldn't quite get it.

### CODE REVIEW

**Comment by gitmstoute** [comment]
@ShahriyarR It is not needed there - that's what I meant about trying to clean up some commits, but I wasn't confident with git. I believe 233f772 creates the conf file, 3d8b995 deletes it again. I was trying to remove these two commits.

**Comment by gitmstoute** [comment]
@ShahriyarR I can take some time to try again and clean up the commits

**Comment by ShahriyarR** [comment]
@gitmstoute It would be great. if you can explain what kind of changes you did, that can be helpful also.
Just few explanations can help me with my tests.

**Comment by gitmstoute** [comment]
I'll resubmit a different PR

**Comment by BarbzYHOOL** [comment]
Note: shahriyarR can squash all your commits into one when merging, for a clean history

**Pull request closed without merging**
